import { WeatherDailyModel } from "../models/WeatherDaily.model";
import { WeatherHourlyModel } from "../models/WeatherHourly..model";

export const MockDataDaily: WeatherDailyModel[] = [
  {
    apparent_temperature_max: { in_c: 20.5, in_f: 68.9 },
    apparent_temperature_min: { in_c: 5.6, in_f: 42.1 },
    daylight_duration: "12:15:3",
    precipitation_hours: {
      unit: "AM",
      has_precipitation: false,
      hour_of_day: 0.0,
    },
    precipitation_probability_max: "0%",
    precipitation_sum: "0.0mm",
    rain_sum: "0.0mm",
    showers_sum: "0.0mm",
    snowfall_sum: "0.0mm",
    sunrise: {
      format: "unix",
      unix: 1726894054,
      event_in_days: -0.0,
      event_in_hours: -8.0,
      event_in_seconds: -32176,
    },
    sunset: {
      format: "unix",
      unix: 1726938167,
      event_in_days: 1.0,
      event_in_hours: 4.0,
      event_in_seconds: 11937,
    },
    sunshine_duration: "10:24:2",
    temperature_2m_max: { in_c: 23.4, in_f: 74.1 },
    temperature_2m_min: { in_c: 7.3, in_f: 45.1 },
    time: {
      format: "unix",
      unix: 1726876800,
      event_in_days: -0.0,
      event_in_hours: -13.0,
      event_in_seconds: -49430,
    },
    uv_index_clear_sky_max: 4.1,
    uv_index_max: 3.9,
    weather_code: "Overcast",
    wind_gusts_10m_max: { km_per_h: 27.4, m_per_s: 7.61 },
    wind_speed_10m_max: { km_per_h: 15.8, m_per_s: 4.39 },
  },
  {
    apparent_temperature_max: { in_c: 22.5, in_f: 72.5 },
    apparent_temperature_min: { in_c: 7.5, in_f: 45.5 },
    daylight_duration: "12:10:58",
    precipitation_hours: {
      unit: "AM",
      has_precipitation: false,
      hour_of_day: 0.0,
    },
    precipitation_probability_max: "0%",
    precipitation_sum: "0.0mm",
    rain_sum: "0.0mm",
    showers_sum: "0.0mm",
    snowfall_sum: "0.0mm",
    sunrise: {
      format: "unix",
      unix: 1726980555,
      event_in_days: 1.0,
      event_in_hours: 16.0,
      event_in_seconds: 54325,
    },
    sunset: {
      format: "unix",
      unix: 1727024423,
      event_in_days: 2.0,
      event_in_hours: 28.0,
      event_in_seconds: 98193,
    },
    sunshine_duration: "10:30:49",
    temperature_2m_max: { in_c: 23.9, in_f: 75.0 },
    temperature_2m_min: { in_c: 8.6, in_f: 47.5 },
    time: {
      format: "unix",
      unix: 1726963200,
      event_in_days: 1.0,
      event_in_hours: 11.0,
      event_in_seconds: 36970,
    },
    uv_index_clear_sky_max: 4.1,
    uv_index_max: 4.1,
    weather_code: "Partly Cloudy",
    wind_gusts_10m_max: { km_per_h: 24.5, m_per_s: 6.81 },
    wind_speed_10m_max: { km_per_h: 13.0, m_per_s: 3.61 },
  },
];

export const MockDataHourly: WeatherHourlyModel[] = [
  {
    apparent_temperature: { in_c: 8.8, in_f: 47.8 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "77%",
    time: {
      format: "unix",
      unix: 1726876800,
      event_in_days: -0.0,
      event_in_hours: -13.0,
      event_in_seconds: -49484,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 42.54, distance_in_meter: 42540.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 8.2, in_f: 46.8 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "79%",
    time: {
      format: "unix",
      unix: 1726880400,
      event_in_days: -0.0,
      event_in_hours: -12.0,
      event_in_seconds: -45884,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 39.3, distance_in_meter: 3.93e4 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 7.7, in_f: 45.9 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "81%",
    time: {
      format: "unix",
      unix: 1726884000,
      event_in_days: -0.0,
      event_in_hours: -11.0,
      event_in_seconds: -42284,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 35.5, distance_in_meter: 3.55e4 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 6.5, in_f: 43.7 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "88%",
    time: {
      format: "unix",
      unix: 1726887600,
      event_in_days: -0.0,
      event_in_hours: -10.0,
      event_in_seconds: -38684,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 19.74, distance_in_meter: 19740.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 6.2, in_f: 43.2 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "87%",
    time: {
      format: "unix",
      unix: 1726891200,
      event_in_days: -0.0,
      event_in_hours: -9.0,
      event_in_seconds: -35084,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 21.4, distance_in_meter: 2.14e4 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 5.6, in_f: 42.1 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "88%",
    time: {
      format: "unix",
      unix: 1726894800,
      event_in_days: -0.0,
      event_in_hours: -8.0,
      event_in_seconds: -31484,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 18.58, distance_in_meter: 18580.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 6.2, in_f: 43.2 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "91%",
    time: {
      format: "unix",
      unix: 1726898400,
      event_in_days: -0.0,
      event_in_hours: -7.0,
      event_in_seconds: -27884,
    },
    uv_index: 0.3,
    visibility: { distance_in_km: 11.7, distance_in_meter: 1.17e4 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 9.4, in_f: 48.9 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "79%",
    time: {
      format: "unix",
      unix: 1726902000,
      event_in_days: -0.0,
      event_in_hours: -6.0,
      event_in_seconds: -24284,
    },
    uv_index: 1.0,
    visibility: { distance_in_km: 33.62, distance_in_meter: 33620.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 13.1, in_f: 55.6 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "66%",
    time: {
      format: "unix",
      unix: 1726905600,
      event_in_days: -0.0,
      event_in_hours: -5.0,
      event_in_seconds: -20684,
    },
    uv_index: 2.0,
    visibility: { distance_in_km: 55.7, distance_in_meter: 5.57e4 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 16.1, in_f: 61.0 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "59%",
    time: {
      format: "unix",
      unix: 1726909200,
      event_in_days: -0.0,
      event_in_hours: -4.0,
      event_in_seconds: -17084,
    },
    uv_index: 2.85,
    visibility: { distance_in_km: 64.62, distance_in_meter: 64620.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 18.5, in_f: 65.3 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "53%",
    time: {
      format: "unix",
      unix: 1726912800,
      event_in_days: -0.0,
      event_in_hours: -3.0,
      event_in_seconds: -13484,
    },
    uv_index: 3.4,
    visibility: { distance_in_km: 70.98, distance_in_meter: 70980.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 19.7, in_f: 67.5 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "43%",
    time: {
      format: "unix",
      unix: 1726916400,
      event_in_days: -0.0,
      event_in_hours: -2.0,
      event_in_seconds: -9884,
    },
    uv_index: 3.9,
    visibility: { distance_in_km: 75.72, distance_in_meter: 75720.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 20.1, in_f: 68.2 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "36%",
    time: {
      format: "unix",
      unix: 1726920000,
      event_in_days: -0.0,
      event_in_hours: -1.0,
      event_in_seconds: -6284,
    },
    uv_index: 3.9,
    visibility: { distance_in_km: 77.32, distance_in_meter: 77320.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 20.5, in_f: 68.9 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "34%",
    time: {
      format: "unix",
      unix: 1726923600,
      event_in_days: -0.0,
      event_in_hours: -0.0,
      event_in_seconds: -2684,
    },
    uv_index: 3.55,
    visibility: { distance_in_km: 78.02, distance_in_meter: 78020.0 },
    weather_code: "Partly Cloudy",
  },
  {
    apparent_temperature: { in_c: 20.5, in_f: 68.9 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "34%",
    time: {
      format: "unix",
      unix: 1726927200,
      event_in_days: 1.0,
      event_in_hours: 1.0,
      event_in_seconds: 916,
    },
    uv_index: 2.8,
    visibility: { distance_in_km: 78.14, distance_in_meter: 78140.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 20.4, in_f: 68.7 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "36%",
    time: {
      format: "unix",
      unix: 1726930800,
      event_in_days: 1.0,
      event_in_hours: 2.0,
      event_in_seconds: 4516,
    },
    uv_index: 1.8,
    visibility: { distance_in_km: 77.62, distance_in_meter: 77620.0 },
    weather_code: "Mainly Clear",
  },
  {
    apparent_temperature: { in_c: 19.6, in_f: 67.3 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "47%",
    time: {
      format: "unix",
      unix: 1726934400,
      event_in_days: 1.0,
      event_in_hours: 3.0,
      event_in_seconds: 8116,
    },
    uv_index: 0.9,
    visibility: { distance_in_km: 75.52, distance_in_meter: 75520.0 },
    weather_code: "Overcast",
  },
  {
    apparent_temperature: { in_c: 17.1, in_f: 62.8 },
    is_day: true,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "59%",
    time: {
      format: "unix",
      unix: 1726938000,
      event_in_days: 1.0,
      event_in_hours: 4.0,
      event_in_seconds: 11716,
    },
    uv_index: 0.2,
    visibility: { distance_in_km: 69.06, distance_in_meter: 69060.0 },
    weather_code: "Overcast",
  },
  {
    apparent_temperature: { in_c: 14.9, in_f: 58.8 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "67%",
    time: {
      format: "unix",
      unix: 1726941600,
      event_in_days: 1.0,
      event_in_hours: 5.0,
      event_in_seconds: 15316,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 58.56, distance_in_meter: 58560.0 },
    weather_code: "Overcast",
  },
  {
    apparent_temperature: { in_c: 13.8, in_f: 56.8 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "73%",
    time: {
      format: "unix",
      unix: 1726945200,
      event_in_days: 1.0,
      event_in_hours: 6.0,
      event_in_seconds: 18916,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 50.28, distance_in_meter: 50280.0 },
    weather_code: "Overcast",
  },
  {
    apparent_temperature: { in_c: 12.9, in_f: 55.2 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "77%",
    time: {
      format: "unix",
      unix: 1726948800,
      event_in_days: 1.0,
      event_in_hours: 7.0,
      event_in_seconds: 22516,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 45.86, distance_in_meter: 45860.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 11.4, in_f: 52.5 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "81%",
    time: {
      format: "unix",
      unix: 1726952400,
      event_in_days: 1.0,
      event_in_hours: 8.0,
      event_in_seconds: 26116,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 36.2, distance_in_meter: 3.62e4 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 10.4, in_f: 50.7 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "84%",
    time: {
      format: "unix",
      unix: 1726956000,
      event_in_days: 1.0,
      event_in_hours: 9.0,
      event_in_seconds: 29716,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 28.28, distance_in_meter: 28280.0 },
    weather_code: "Clear Sky",
  },
  {
    apparent_temperature: { in_c: 9.7, in_f: 49.5 },
    is_day: false,
    precipitation: "0.0mm",
    precipitation_probability: "0%",
    relative_humidity_2m: "86%",
    time: {
      format: "unix",
      unix: 1726959600,
      event_in_days: 1.0,
      event_in_hours: 10.0,
      event_in_seconds: 33316,
    },
    uv_index: 0.0,
    visibility: { distance_in_km: 23.08, distance_in_meter: 23080.0 },
    weather_code: "Clear Sky",
  },
];
